config/routes.rb
CdDemo::Application.routes.draw do
  resources :albums
  resource :search_results, :only => :show

  namespace :services do
    resources :albums
    resource :search_results, :only => :show
  end

  root :to => 'app#show'

end

app/models/album.rb
class Album < ApiResource
  self.collection_name = 'albums'

  schema do
    string 'artist', 'title'
  end
end

app/models/api_resource.rb
class ApiResource < ActiveResource::Base
  self.site = "http://localhost:4000/services/"
  self.format = :json
end

app/models/search_results.rb
class SearchResults < ApiResource
  self.collection_name = 'search_results'

  def self.query(search_string)
    if search_string.blank?
      []
    else
      find(:all, :params => { :q => search_string })
    end
  end
end

app/models/services/album.rb
class Services::Album < ActiveRecord::Base
  attr_accessible :artist, :title

  validates :artist, :title, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  respond_to :html

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    @album.save
    respond_with @album, :location => albums_path
  end

  def index
    @albums = Album.all
    respond_with @albums
  end

  def show
    @album = Album.find(params[:id])
    respond_with @album
  end

  def edit
    @album = Album.find(params[:id])
    respond_with @album
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(params[:album])
    respond_with @album, :location => albums_path
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  def show
    @search_results = SearchResults.query(params[:q])
  end
end

app/controllers/services/albums_controller.rb
class Services::AlbumsController < Services::ApiController
  def create
    @album = Services::Album.new(params[:album])
    @album.save
    respond_with @album
  end

  def index
    @albums = Services::Album.all
    respond_with @albums
  end

  def show
    @album = Services::Album.find(params[:id])
    respond_with @album
  end

  def update
    @album = Services::Album.find(params[:id])
    @album.update_attributes(params[:album])
    respond_with @album
  end

  def destroy
    @album = Services::Album.find(params[:id])
    @album.destroy
    respond_with @album
  end
end

app/controllers/services/api_controller.rb
class Services::ApiController < ApplicationController
  respond_to :json
end

app/controllers/services/search_results_controller.rb
class Services::SearchResultsController < Services::ApiController
  def show
    q = "%#{params[:q]}%"
    @search_results = Services::Album.where("artist LIKE ? OR title LIKE ?", q, q)
    respond_with @search_results
  end
end

app/views/albums/_album.html.erb
<%= album.artist %>: <%= link_to album.title, album_path(album) %>

app/views/albums/_form.html.erb
<% if @album.errors.any? -%>
  <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end -%>

<%= semantic_form_for @album do |f| %>
  <%= f.inputs :artist, :title %>
  <%= f.actions %>
  <p><%= link_to "Cancel", albums_path %></p>
<% end -%>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form" %>

app/views/albums/index.html.erb
<h1>All Albums</h1>

<ul>
  <% @albums.each do |album| -%>
    <il><%= render :partial => '/albums/album', :locals => { :album => album } %></il>
  <% end -%>
</ul>

<ul>
  <li><%= link_to "New album", new_album_path %></li>
  <li><%= link_to "Home", root_path %></li>
</ul>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "form" %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<p>Artist: <%= @album.artist %></p>

<ul>
  <li><%= link_to "Edit", edit_album_path(@album) %></li>
  <li><%= button_to "Delete", album_path(@album), :method => :delete %></li>
  <li><%= link_to "All albums", albums_path %></li>
  <li><%= link_to "Home", root_path %></li>
</ul>

app/views/app/show.html.erb
<h1>CD-Demo</h1>

<p>With this tiny demo app you can manage and search cd data through a web service.</p>

<%= render :partial => "search_results/form" %>

<p><%= link_to "Manage albums", albums_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CD-Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search_results/_form.html.erb
<%= form_tag search_results_path, :method => 'get' do |f| %>
  <p>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Find", :name => nil %>
  </p>
<% end -%>

app/views/search_results/show.html.erb
<h1>Search</h1>

<%= render :partial => "search_results/form" %>

<% if @search_results.any? -%>
  <ul>
    <% @search_results.each do |search_result| -%>
      <il><%= render :partial => '/albums/album', :locals => { :album => search_result } %></il>
    <% end -%>
  </ul>
<% elsif params[:q].present? -%>
  <p>not found</p>
<% end -%>

<p><%= link_to "Home", root_path %></p>